### ISSUE TITLE
no file processing

### ISSUE THREAD

**Issue by nonofr91** [andrey18106/mediadc#100]
![Capture d’écran 2023-01-04 182316](https://user-images.githubusercontent.com/120282967/210613537-52908e58-0783-443f-b36f-8498e92d03d0.png)

The installation seems to have been done correctly. But no file processing is done.
How to see the logs or other to know where it is blocking.

**Comment by andrey18106** [comment]
@nonofr91 Hi, you can find logs in `nextcloud/data/appdata_instanceid/mediadc/logs` folder. Please, verify it and let us know what's your system configuration.

**Comment by andrey18106** [comment]
@nonofr91 Hi, you can find logs in `nextcloud/data/appdata_instanceid/mediadc/logs` folder. Please, verify it and let us know what's your system configuration.

**Comment by nonofr91** [comment]
thank you
Here is the content of the log files which are always the same:

nohup: failed to run command '/data/appdata_ocnahsfazjip/mediadc/binaries/main': No such file or directory
I think I installed the application in the wrong directory because I don't see anything in the user directories.

this is probably when I had to install the dependencies in console mode.

I will try to uninstall and start over.

**Comment by andrey18106** [comment]
@nonofr91 Seems like not proper installation, check out [wiki 0.3.0 notice](https://github.com/andrey18106/mediadc/wiki#mediadc-030-important-notice).

**Comment by nonofr91** [comment]
here are the installation logs:
But that didn't solve my problem.

root@omv:/srv/dev-disk-by-uuid-8a83f4f8-a633-4709-b381-84c1d5aca732/appdata/nextcloud/data/appdata_ocnahsfazjip/mediadc# python3 -m pip install -r requirements.txt
/usr/bin/python3: No module named pip
root@omv:/srv/dev-disk-by-uuid-8a83f4f8-a633-4709-b381-84c1d5aca732/appdata/nextcloud/data/appdata_ocnahsfazjip/mediadc# sudo apt install python3-distutils -y

Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Les paquets supplémentaires suivants seront installés : 
  python3-lib2to3
Les NOUVEAUX paquets suivants seront installés :
  python3-distutils python3-lib2to3
0 mis à jour, 2 nouvellement installés, 0 à enlever et 3 non mis à jour.
Il est nécessaire de prendre 221 ko dans les archives.
Après cette opération, 1 086 ko d'espace disque supplémentaires seront utilisés.
Réception de :1 http://deb.debian.org/debian bullseye/main amd64 python3-lib2to3 all 3.9.2-1 [77,8 kB]
Réception de :2 http://deb.debian.org/debian bullseye/main amd64 python3-distutils all 3.9.2-1 [143 kB]
221 ko réceptionnés en 0s (881 ko/s)         
Sélection du paquet python3-lib2to3 précédemment désélectionné.
(Lecture de la base de données... 36543 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../python3-lib2to3_3.9.2-1_all.deb ...
Dépaquetage de python3-lib2to3 (3.9.2-1) ...
Sélection du paquet python3-distutils précédemment désélectionné.
Préparation du dépaquetage de .../python3-distutils_3.9.2-1_all.deb ...
Dépaquetage de python3-distutils (3.9.2-1) ...
Paramétrage de python3-lib2to3 (3.9.2-1) ...
Paramétrage de python3-distutils (3.9.2-1) ...
root@omv:/srv/dev-disk-by-uuid-8a83f4f8-a633-4709-b381-84c1d5aca732/appdata/nextcloud/data/appdata_ocnahsfazjip/mediadc# sudo apt install python3-pip -y

Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Les paquets supplémentaires suivants seront installés : 
  python-pip-whl python3-setuptools python3-wheel
Paquets suggérés :
  python-setuptools-doc
Paquets recommandés :
  build-essential python3-dev
Les NOUVEAUX paquets suivants seront installés :
  python-pip-whl python3-pip python3-setuptools python3-wheel
0 mis à jour, 4 nouvellement installés, 0 à enlever et 3 non mis à jour.
Il est nécessaire de prendre 2 676 ko dans les archives.
Après cette opération, 5 313 ko d'espace disque supplémentaires seront utilisés.
Réception de :1 http://deb.debian.org/debian bullseye/main amd64 python-pip-whl all 20.3.4-4+deb11u1 [1 948 kB]
Réception de :2 http://deb.debian.org/debian bullseye/main amd64 python3-setuptools all 52.0.0-4 [366 kB]
Réception de :3 http://deb.debian.org/debian bullseye/main amd64 python3-wheel all 0.34.2-1 [24,0 kB]
Réception de :4 http://deb.debian.org/debian bullseye/main amd64 python3-pip all 20.3.4-4+deb11u1 [337 kB]
2 676 ko réceptionnés en 0s (15,4 Mo/s)
Sélection du paquet python-pip-whl précédemment désélectionné.
(Lecture de la base de données... 36682 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../python-pip-whl_20.3.4-4+deb11u1_all.deb ...
Dépaquetage de python-pip-whl (20.3.4-4+deb11u1) ...
Sélection du paquet python3-setuptools précédemment désélectionné.
Préparation du dépaquetage de .../python3-setuptools_52.0.0-4_all.deb ...
Dépaquetage de python3-setuptools (52.0.0-4) ...
Sélection du paquet python3-wheel précédemment désélectionné.
Préparation du dépaquetage de .../python3-wheel_0.34.2-1_all.deb ...
Dépaquetage de python3-wheel (0.34.2-1) ...
Sélection du paquet python3-pip précédemment désélectionné.
Préparation du dépaquetage de .../python3-pip_20.3.4-4+deb11u1_all.deb ...
Dépaquetage de python3-pip (20.3.4-4+deb11u1) ...
Paramétrage de python3-setuptools (52.0.0-4) ...
Paramétrage de python3-wheel (0.34.2-1) ...
Paramétrage de python-pip-whl (20.3.4-4+deb11u1) ...
Paramétrage de python3-pip (20.3.4-4+deb11u1) ...
root@omv:/srv/dev-disk-by-uuid-8a83f4f8-a633-4709-b381-84c1d5aca732/appdata/nextcloud/data/appdata_ocnahsfazjip/mediadc# python3 -m pip install -r requirements.txt
Collecting pynacl
  Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
     |████████████████████████████████| 856 kB 4.6 MB/s 
Collecting numpy
  Downloading numpy-1.24.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     |████████████████████████████████| 17.3 MB 132.5 MB/s 
Collecting scipy
  Downloading scipy-1.10.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
     |████████████████████████████████| 34.4 MB 97.8 MB/s 
Collecting pywavelets
  Downloading PyWavelets-1.4.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.9 MB)
     |████████████████████████████████| 6.9 MB 23.4 MB/s 
Collecting pillow
  Downloading Pillow-9.4.0-cp39-cp39-manylinux_2_28_x86_64.whl (3.4 MB)
     |████████████████████████████████| 3.4 MB 51.2 MB/s 
Collecting hexhamming
  Downloading hexhamming-2.2.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42 kB)
     |████████████████████████████████| 42 kB 6.2 MB/s 
Collecting nc-py-api>=0.0.8
  Downloading nc_py_api-0.0.9-py3-none-any.whl (25 kB)
Collecting pi-heif>=0.9.0
  Downloading pi_heif-0.9.1-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (969 kB)
     |████████████████████████████████| 969 kB 97.2 MB/s 
Collecting pymysql
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 9.8 MB/s 
Collecting cryptography
  Downloading cryptography-39.0.0-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 104.7 MB/s 
Collecting pg8000
  Downloading pg8000-1.29.4-py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 392 kB/s 
Collecting cffi>=1.14.6
  Downloading cffi-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
     |████████████████████████████████| 441 kB 86.8 MB/s 
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 47.6 MB/s 
Collecting scramp>=1.4.3
  Downloading scramp-1.4.4-py3-none-any.whl (13 kB)
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 45.3 MB/s 
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pg8000->nc-py-api>=0.0.8->-r requirements.txt (line 7)) (1.16.0)
Collecting asn1crypto>=1.5.1
  Downloading asn1crypto-1.5.1-py2.py3-none-any.whl (105 kB)
     |████████████████████████████████| 105 kB 47.6 MB/s 
Installing collected packages: pycparser, asn1crypto, scramp, python-dateutil, cffi, pynacl, pymysql, pillow, pg8000, numpy, cryptography, scipy, pywavelets, pi-heif, nc-py-api, hexhamming
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.1
    Not uninstalling python-dateutil at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'python-dateutil'. No files were found to uninstall.
Successfully installed asn1crypto-1.5.1 cffi-1.15.1 cryptography-39.0.0 hexhamming-2.2.3 nc-py-api-0.0.9 numpy-1.24.1 pg8000-1.29.4 pi-heif-0.9.1 pillow-9.4.0 pycparser-2.21 pymysql-1.0.2 pynacl-1.5.0 python-dateutil-2.8.2 pywavelets-1.4.1 scipy-1.10.0 scramp-1.4.4
root@omv:/srv/dev-disk-by-uuid-8a83f4f8-a633-4709-b381-84c1d5aca732/appdata/nextcloud/data/appdata_ocnahsfazjip/mediadc#

**Comment by nonofr91** [comment]
nohup: failed to run command '/data/appdata_ocnahsfazjip/mediadc/main.py': Permission denied

**Comment by bigcat88** [comment]
First let's be clear, in what mode we are working, in `source` mode or in default binary mode
In binary(default) mode you do not need to install anything additionally.

First question, did you install `cloud_py_api` app before mediadc?

**Comment by nonofr91** [comment]
Not knowing anymore I deactivated and deleted cloud_py_api and MediaDC.
I proceeded with the installation starting with cloud_py_api and following MediaDC.
And still the same problem.

For installing bianaries this is what I read on the wiki https://github.com/andrey18106/mediadc/wiki

**Comment by andrey18106** [comment]
> Not knowing anymore I deactivated and deleted cloud_py_api and MediaDC. I proceeded with the installation starting with cloud_py_api and following MediaDC. And still the same problem.
> 
> For installing bianaries this is what I read on the wiki https://github.com/andrey18106/mediadc/wiki

Does downloaded python binary (in `nextcloud/data/appdata_instanceid/mediadc/binaries`) exists?

What's the output of the following run:

`sudo -u <webserver_user> SERVER_ROOT="/path/to/nextcloud" /path/to/nextcloud/data/appdata_ncinstanceid/mediadc/binaries/main --info`

`<webserver_user>` - your webserver's user (`www-data`, `apache`, or `nginx`).

If it's ok, please verify that python binary processing tasks with:

`sudo -u <webserver_user> SERVER_ROOT="/path/to/nextcloud" LOGLEVEL="DEBUG" CPA_LOGLEVEL="DEBUG" /path/to/nextcloud/data/appdata_ncinstanceid/mediadc/binaries/main -t <mediadc_task_id>`

`<mediadc_task_id>` - last number in the link on task details page.

**Comment by nonofr91** [comment]
main --info:

ERROR:nc_py_api:occ:php_call:php_call exception:
Traceback (most recent call last):
  File "/tmp/onefile_342793_1672915040_699/nc_py_api/occ.py", line 54, in php_call
  File "/tmp/onefile_342793_1672915040_699/subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['php', '/var/www/nextcloud/occ', '--no-warnings', 'config:system:get', 'dbname']' returned non-zero exit status 1.
ERROR:nc_py_api:config:<module nc_py_api.config>:Cant find {dbname} value in NC config.
ERROR:nc_py_api:occ:php_call:php_call exception:
Traceback (most recent call last):
  File "/tmp/onefile_342793_1672915040_699/nc_py_api/occ.py", line 54, in php_call
  File "/tmp/onefile_342793_1672915040_699/subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['php', '/var/www/nextcloud/occ', '--no-warnings', 'config:system:get', 'dbuser']' returned non-zero exit status 1.
ERROR:nc_py_api:config:<module nc_py_api.config>:Cant find {dbuser} value in NC config.
ERROR:nc_py_api:occ:php_call:php_call exception:
Traceback (most recent call last):
  File "/tmp/onefile_342793_1672915040_699/nc_py_api/occ.py", line 54, in php_call
  File "/tmp/onefile_342793_1672915040_699/subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['php', '/var/www/nextcloud/occ', '--no-warnings', 'config:system:get', 'dbpassword']' returned non-zero exit status 1.
ERROR:nc_py_api:config:<module nc_py_api.config>:Cant find {dbpassword} value in NC config.
ERROR:nc_py_api:occ:php_call:php_call exception:
Traceback (most recent call last):
  File "/tmp/onefile_342793_1672915040_699/nc_py_api/occ.py", line 54, in php_call
  File "/tmp/onefile_342793_1672915040_699/subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['php', '/var/www/nextcloud/occ', '--no-warnings', 'config:system:get', 'dbhost']' returned non-zero exit status 1.
ERROR:nc_py_api:config:<module nc_py_api.config>:Cant find {dbhost} value in NC config.
ERROR:nc_py_api:occ:php_call:php_call exception:
Traceback (most recent call last):
  File "/tmp/onefile_342793_1672915040_699/nc_py_api/occ.py", line 54, in php_call
  File "/tmp/onefile_342793_1672915040_699/subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['php', '/var/www/nextcloud/occ', '--no-warnings', 'config:system:get', 'dbtype']' returned non-zero exit status 1.
ERROR:nc_py_api:config:<module nc_py_api.config>:Cant find {dbtype} value in NC config.
ERROR:nc_py_api:occ:php_call:php_call exception:
Traceback (most recent call last):
  File "/tmp/onefile_342793_1672915040_699/nc_py_api/occ.py", line 54, in php_call
  File "/tmp/onefile_342793_1672915040_699/subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['php', '/var/www/nextcloud/occ', '--no-warnings', 'config:system:get', 'datadirectory']' returned non-zero exit status 1.
ERROR:nc_py_api:config:<module nc_py_api.config>:Cant find {datadirectory} value in NC config.
INFO:nc_py_api.mediadc:bundle_info:bundle_info:Python: 3.9.16 (main, Dec 19 2022, 10:54:04) 
[GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
INFO:nc_py_api.mediadc:bundle_info:bundle_info:nc_py_api: 0.0.8
INFO:nc_py_api.mediadc:bundle_info:bundle_info:mediadc: 0.3.0
INFO:nc_py_api.mediadc:bundle_info:bundle_info:pg8000: 1.29.4
INFO:nc_py_api.mediadc:bundle_info:bundle_info:pynacl: 1.5.0
INFO:nc_py_api.mediadc:bundle_info:bundle_info:cryptography: 38.0.4
INFO:nc_py_api.mediadc:bundle_info:bundle_info:pymysql: 1.0.2
INFO:nc_py_api.mediadc:bundle_info:bundle_info:pillow: 9.3.0
INFO:nc_py_api.mediadc:bundle_info:bundle_info:pi_heif: 0.9.0
INFO:nc_py_api.mediadc:bundle_info:bundle_info:numpy: 1.21.4
INFO:nc_py_api.mediadc:bundle_info:bundle_info:scipy: 1.7.2
INFO:nc_py_api.mediadc:bundle_info:bundle_info:pywavelets: 1.4.1

main -t :+1: 
DEBUG:nc_py_api:log:<module nc_py_api.log>:Logger initialized.
ERROR:nc_py_api:occ:php_call:php_call exception:
Traceback (most recent call last):
  File "/tmp/onefile_343911_1672915510_645989/nc_py_api/occ.py", line 54, in php_call
  File "/tmp/onefile_343911_1672915510_645989/subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['php', 'occ', '--no-warnings', 'config:system:get', 'dbname']' returned non-zero exit status 1.
ERROR:nc_py_api:config:<module nc_py_api.config>:Cant find {dbname} value in NC config.
ERROR:nc_py_api:occ:php_call:php_call exception:
Traceback (most recent call last):
  File "/tmp/onefile_343911_1672915510_645989/nc_py_api/occ.py", line 54, in php_call
  File "/tmp/onefile_343911_1672915510_645989/subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['php', 'occ', '--no-warnings', 'config:system:get', 'dbuser']' returned non-zero exit status 1.
ERROR:nc_py_api:config:<module nc_py_api.config>:Cant find {dbuser} value in NC config.
ERROR:nc_py_api:occ:php_call:php_call exception:
Traceback (most recent call last):
  File "/tmp/onefile_343911_1672915510_645989/nc_py_api/occ.py", line 54, in php_call
  File "/tmp/onefile_343911_1672915510_645989/subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['php', 'occ', '--no-warnings', 'config:system:get', 'dbpassword']' returned non-zero exit status 1.
ERROR:nc_py_api:config:<module nc_py_api.config>:Cant find {dbpassword} value in NC config.
ERROR:nc_py_api:occ:php_call:php_call exception:
Traceback (most recent call last):
  File "/tmp/onefile_343911_1672915510_645989/nc_py_api/occ.py", line 54, in php_call
  File "/tmp/onefile_343911_1672915510_645989/subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['php', 'occ', '--no-warnings', 'config:system:get', 'dbhost']' returned non-zero exit status 1.
ERROR:nc_py_api:config:<module nc_py_api.config>:Cant find {dbhost} value in NC config.
ERROR:nc_py_api:occ:php_call:php_call exception:
Traceback (most recent call last):
  File "/tmp/onefile_343911_1672915510_645989/nc_py_api/occ.py", line 54, in php_call
  File "/tmp/onefile_343911_1672915510_645989/subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['php', 'occ', '--no-warnings', 'config:system:get', 'dbtype']' returned non-zero exit status 1.
ERROR:nc_py_api:config:<module nc_py_api.config>:Cant find {dbtype} value in NC config.
ERROR:nc_py_api:occ:php_call:php_call exception:
Traceback (most recent call last):
  File "/tmp/onefile_343911_1672915510_645989/nc_py_api/occ.py", line 54, in php_call
  File "/tmp/onefile_343911_1672915510_645989/subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['php', 'occ', '--no-warnings', 'config:system:get', 'datadirectory']' returned non-zero exit status 1.
ERROR:nc_py_api:config:<module nc_py_api.config>:Cant find {datadirectory} value in NC config.

**Comment by bigcat88** [comment]
We see that binary look ok, it is normal logs when run it from terminal in this case. You still get `permission denied` when trying to start task from WebUI or some another error?

**Comment by Winnize-ops** [comment]
Hello,

First of all, thank you for your work.
I have exactly the same configuration as nono (openmediavault, portainer/docker) and unfortunately the same symptom.
For my part I use the default "admin" account of Openmediavault for Nextcloud which has the rights on folders and files.
{
  "nextcloud-version": "25.0.2.3",
  "app-versions": {
    "cloud_py_api-version": "0.1.2",
    "mediadc-version": "0.3.2"
  },
  "is-videos-supported": true,
  "is-snap": false,
  "arch": "aarch64",
  "webserver": "nginx/1.20.2",
  "database": {
    "type": "mysql",
    "version": "10.6.10",
    "size": "53723136"
  },
  "php-version": "8.0.25",
  "php-interpreter": "/usr/bin/php",
  "python-interpreter-setting": "/usr/bin/python3",
  "os": "Linux",
  "os-release": "6.0.13-meson64",
  "machine-type": "aarch64"
},

**Comment by bigcat88** [comment]
@Winnize-ops post the size of binary file please, we fixed this on cloud_py_api 0.1.2 already... did you install MediaDC after cloud_py_api 0.1.2?

**Comment by bigcat88** [comment]
@Winnize-ops from another folder

root@4c44918a822e:/# ls -la /data/appdata_ocr5kkmye0u5/mediadc/binaries/
total 164148
drwxr-xr-x 2 abc abc      4096 Jan 18 20:01 .
drwxr-xr-x 4 abc abc      4096 Jan 18 20:01 ..
-rwxr-xr-x 1 abc abc 168071902 Jan 18 20:01 main

`appdata_ocr5kkmye0u5` in your case will be different and size of binary too, and to diagnose i need to know that binary was downloaded successfully by it's size that you wil ltell me.

**Comment by Winnize-ops** [comment]
winnize@odroidhc4:~/Nextcloud/data/appdata_oc8h8732v004/mediadc/binaries$ ls -la
total 4
drwxr-xr-x 1 admin users  8 Jan 18 19:33 .
drwxr-xr-x 1 admin users 24 Jan 18 19:33 ..
-rwxr-xr-x 1 admin users  9 Jan 18 19:33 main

Indeed the size does not correspond to the value you stipulate, thank you for the instructions.

**Comment by bigcat88** [comment]
and where is size? =)

**Comment by bigcat88** [comment]
wait for update on cloud_py_api 0.1.3, for now remove them both. thanks for reporting this, next update should work for arm64 too.

**Comment by Winnize-ops** [comment]
Thank you for your actions and your feedback.

Good luck 🙂

**Comment by andrey18106** [comment]
@Winnize-ops We have published cloud_py_api 0.1.3 with arm64 hotfix, when it'll appear in your Nextcloud, try again please and let us know if it works or not. Thanks for info.

**Comment by Winnize-ops** [comment]
Hello,

It works :

![Screenshot_2023-01-19-06-50-12-180-edit_com.brave.browser.jpg](https://user-images.githubusercontent.com/123011396/213365749-3d371516-ca4a-442c-8359-67394448d7da.jpg)

winnize@odroidhc4:~/Nextcloud/data/appdata_oc8h8732v004/mediadc/binaries$ ls -la
total 134288
drwxr-xr-x 1 admin users         8 Jan 19 06:31 .
drwxr-xr-x 1 admin users        24 Jan 19 06:31 ..
-rwxr-xr-x 1 admin users 137509807 Jan 19 06:31 main

winnize@odroidhc4:~/Nextcloud/data/appdata_oc8h8732v004/mediadc$ du -h
132M    ./binaries
4.0K    ./logs
132M    .

Thank you again and have a nice day.
