### ISSUE TITLE
Configuration errors: db_exception_handler:

### ISSUE THREAD

**Issue by isaacolsen94** [andrey18106/mediadc#11]
**Describe the bug**
Installed the first time using v0.1.1, recieved a "Configuration error". Tried re-installing and wouldn't go away. Saw v0.1.2 was released so I updated to that the next day. When I reinstalled after the update it still gave me the same errors. I've pasted the output below. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Browser: Firefox
 - Nextcloud version: 22.1.1
 - MediaDC version: v0.1.2

**Additional context**
![image](https://user-images.githubusercontent.com/52682311/135696410-62764d04-aa2c-4fe2-8bae-4f99f3113c52.png)

db_exception_handler:

Traceback (most recent call last):

  File "/var/www/nextcloud/apps/mediadc/lib/Service/python/db/pymysql/connections.py", line 613, in connect

    sock = socket.create_connection(

  File "/usr/lib/python3.8/socket.py", line 787, in create_connection

    for res in getaddrinfo(host, port, 0, SOCK_STREAM):

  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/var/www/nextcloud/apps/mediadc/lib/Service/python/db/connectors.py", line 44, in create_connection

    connection = pymysql.connect(host=config['dbhost'],

  File "/var/www/nextcloud/apps/mediadc/lib/Service/python/db/pymysql/connections.py", line 352, in __init__

    self.connect()

  File "/var/www/nextcloud/apps/mediadc/lib/Service/python/db/pymysql/connections.py", line 664, in connect

    raise exc

db.pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '10.10.10.33:3306' ([Errno -2] Name or service not known)")

Cant connect to database.`

**Comment by bigcat88** [comment]
Hi! Thanks you for this bug report.

Can you provide some more additional info about your configuration, for faster investigation.

1. As I see database are in another docker/container image or another pc, is that correct?
2. Can  you post  your `dbhost` value from nextcloud/config/config.php (ofc  with replaced sensitive data, just for us to understand what format of string is there) Do you have in `dbhost` both host  and port?
 Like: 'dbhost' => 'x.x.x.x:3306'?
3. Do you configured DB for cloud in php? (pdo_mysql)

**Comment by bigcat88** [comment]
Ok, we were able to reproduce this error(we forgot that port can be specified not in `dbport` but after ip in config), will fix soon.

**Comment by isaacolsen94** [comment]
Sorry I was asleep. I can confirm that my config file has the port listed with the ip address: 
'dbhost' => '10.10.10.33:3306',

Do you need any more info from me?

**Comment by bigcat88** [comment]
> Sorry I was asleep, but thank you for looking at this! I can confirm that my config file has the port listed with the ip address: 'dbhost' => '10.10.10.33:3306',
> 
> Do you need any more info from me?

No, we will post fix tomorrow or at Monday, thanks you for issue.

**Comment by bigcat88** [comment]
@isaacolsen94 fixed in 0.1.3
