### ISSUE TITLE
Add instructions to Alpine Linux/Docker

### ISSUE THREAD

**Issue by LeoColman** [andrey18106/mediadc#27]
A lot of nextcloud instances are installed in a docker or docker-compose environment.

We should have a setup guide on how to do that

**Comment by andrey18106** [comment]
@LeoColman Hi! Yea, we will surely write in our docs about how to adjust Docker Compose configuration to use MediaDC, in particular how to add Python 3 and other required packages (`distutils`, `ffmpeg`). We just need to learn and test all ourselves, keep on waiting)

**Comment by timbeglinger** [comment]
On Nextcloud 23 with **Postgres 13**, this Dockerfile works for me:

```Dockerfile
FROM nextcloud:23.0.0-fpm-alpine

RUN set -ex; \
    \
    apk add --no-cache \
    ffmpeg \
    imagemagick \
    supervisor \
    py3-numpy \
    py3-pillow \
    py3-asn1crypto \
    ;

RUN mkdir -p \
    /var/log/supervisord \
    /var/run/supervisord \
    ;

COPY supervisord.conf /

ENV NEXTCLOUD_UPDATE=1

CMD ["/usr/bin/supervisord", "-c", "/supervisord.conf"]
```

With **mysql/mariadb**, it should probably be:
```Dockerfile
FROM nextcloud:23.0.0-fpm-alpine

RUN set -ex; \
    \
    apk add --no-cache \
    ffmpeg \
    imagemagick \
    supervisor \
    py3-numpy \
    py3-pillow \
    py3-pynacl \
    py3-cryptography \
    ;

RUN mkdir -p \
    /var/log/supervisord \
    /var/run/supervisord \
    ;

COPY supervisord.conf /

ENV NEXTCLOUD_UPDATE=1

CMD ["/usr/bin/supervisord", "-c", "/supervisord.conf"]
```

**Comment by romprod** [comment]
I've tried both your dockerfile's above but I get the following error when building.

I can download both tar files successfully on the same host etc.

`Building nextcloud
Sending build context to Docker daemon  2.048kB
Step 1/6 : FROM nextcloud:23.0.0-fpm-alpine
 ---> 133f789a3fd7
Step 2/6 : RUN set -ex;         apk add --no-cache     ffmpeg     imagemagick     supervisor     py3-numpy     py3-pillow     py3-pynacl     py3-cryptography     ;
 ---> Running in 54f67114e38a
+ apk add --no-cache ffmpeg imagemagick supervisor py3-numpy py3-pillow py3-pynacl py3-cryptography
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: temporary error (try again later)
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: temporary error (try again later)
ERROR: unable to select packages:
  ffmpeg (no such package):
    required by: world[ffmpeg]
  imagemagick (no such package):
    required by: world[imagemagick]
  py3-cryptography (no such package):
    required by: world[py3-cryptography]
  py3-numpy (no such package):
    required by: world[py3-numpy]
  py3-pillow (no such package):
    required by: world[py3-pillow]
  py3-pynacl (no such package):
    required by: world[py3-pynacl]
  supervisor (no such package):
    required by: world[supervisor]
The command '/bin/sh -c set -ex;         apk add --no-cache     ffmpeg     imagemagick     supervisor     py3-numpy     py3-pillow     py3-pynacl     py3-cryptography     ;' returned a non-zero code: 7
ERROR: Service 'nextcloud' failed to build : Build failed`

**Comment by andrey18106** [comment]
MediaDC Docker Alpine example available [here](https://github.com/andrey18106/mediadc-docker-example).
