### ISSUE TITLE
Cant find `dbtableprefix` value in cloud config

### ISSUE THREAD

**Issue by xkill** [andrey18106/mediadc#28]
**Describe the bug**
After performing the automated installation of deps I got the error:
```
Cant find `dbtableprefix` value in cloud config
```

**To Reproduce**
1. Install plugin
2. Go to MediaDC preferences
3. Click on "Check installation"

**Expected behavior**
If the `dbtableprefix` is not defined get this value from default settings. In this case this value is `oc_`

**Desktop (please complete the following information):**
 - Nextcloud 22.2.3
 - Database configuration. using MariaDB with default dbtableprefix (`oc_`)
 - Python 3.8.10
 - MediaDC 0.1.7

**Comment by bigcat88** [comment]
Do you have in your config file located at NEXTCLOUD_FOLDER`/config/config.php` value `dbtableprefix` ?
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=dbtableprefix

**Comment by xkill** [comment]
> 

This is the work around. To manually add the dbtableprefix to the config.php, but the application should get the default value (if it is not defined) in order to work fine.

**Comment by bigcat88** [comment]
But it helps? Or problem is somewhere else?
I agree with you that it is a workaround, you are right, if it works when you add `dbtableprefix` then we know where to fix it, and will fix it.
Next update(with fix for shared directories scan and GUI improvements) planned  in close future, with  a couple of days.

**Comment by bigcat88** [comment]
@xkill Fixed in 0.1.8
