### ISSUE TITLE
Automatically open next duplicate group after closing the last one

### ISSUE THREAD

**Issue by RedSackles** [andrey18106/mediadc#30]
As a user having to review hundresds suggested deletions I find the tool great but the interface somewhat clunky to use.
When finished with one duplicate group it removes it from the list and you have to open the next one.
Depending on when you click the next duplicate group the list will jump on you as one duplicate group opens and the last one gets removed from the list.

The request is to 
- have the option for it to automatically open the next duplicate group in line once you have resolved one duplicate group.
- Alternatively have the option to open all duplicate groups as they are loaded but then set the number of duplicate groups per page to one.

**Comment by bigcat88** [comment]
@RedSackles we make some improvements in a new 0.1.8 version, w8 for comments. =)

**Comment by RedSackles** [comment]
Thank you. Looking forward to checking out the update.
