### ISSUE TITLE
In addition to delete have an ignore option

### ISSUE THREAD

**Issue by RedSackles** [andrey18106/mediadc#31]
When reviewing duplicate groups I come across images that are indeed rather similar but I still want to keep both images .

What I am missing is the option to ignore these duplicate groups as false-positive/ignored images and have the duplicate group drop from the list as resolved.
Preferably also have those false-positive/ignored images no longer show up in future jobs unless a new (not jet ignored) image is found that matches a previously ignored image.

**Comment by andrey18106** [comment]
Added "Resolved" in [MediaDC 0.1.10](https://github.com/andrey18106/mediadc/releases/tag/v0.1.10). Closing.
