### ISSUE TITLE
scan task returns error state

### ISSUE THREAD

**Issue by petervanderreest** [andrey18106/mediadc#32]
Dear all,
thanks for your efforts on duplicate identification!
I have installed the software seemingly without any problems, but when a regular user runs a scan across her photo library, the task returns with an error. It would be great if the end user would be able to see some more info on the error that occured.
Now it is always up to the admin to go bug hunting. In small installations that's OK, but with 3000+ users will not scale.
Thanks,
Peter.

**Comment by bigcat88** [comment]
@petervanderreest We will post update in a few hours, please check on it, and new version didn't solve it, provide a bit more info :)
