### ISSUE TITLE
Batch working on results of tasks

### ISSUE THREAD

**Issue by ykutovoy** [andrey18106/mediadc#36]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/13015154/147248011-1f7143b5-6df7-41d3-85cb-f0c222b53a87.png">

**Description**
As You can see on screenshot I've got a plenty of groups in this task.
**It would be nice to add checkbox "Select ALL"**

Also pay attention that on screen we have 4 marks, but in Batch menu (right corner) 8 selections
It happens when I searched groups with "20" first and select first 4 groups, than switched to "100" and selected other 4
**Good idea to show all selected numbers at once**

And once more
is it possible to **add in filter ranges**.... like in printers wen you select what to print...
42-500; 3; 7; 1024-

**Comment by andrey18106** [comment]
@ykutovoy Thanks you for your remarks. We will think about it, good suggestions.

**Comment by andrey18106** [comment]
Added in [MediaDC 0.1.10](https://github.com/andrey18106/mediadc/releases/tag/v0.1.10). Closing.
