### ISSUE TITLE
Group number in results

### ISSUE THREAD

**Issue by ykutovoy** [andrey18106/mediadc#38]
first run
![image](https://user-images.githubusercontent.com/13015154/147341683-d4ac1689-e21d-4a46-86f0-f794b7ac94b9.png)

next run
<img width="404" alt="image" src="https://user-images.githubusercontent.com/13015154/147342023-6272da6e-5faf-43da-9735-53abed6fb02e.png">

I'm not sure, if it is a bug, but
If You restart task, resulting groups numbers not starting from beginning, but increments from previous task start.

**Comment by andrey18106** [comment]
@ykutovoy No, it's not a bug, that's because for each task run old details are deleted and therefore for the new details we have new ids.

**Comment by ykutovoy** [comment]
I think it is not a problem, but if we deleting old details, why not we deleting the numbers of that details?
Just starting from 1 on each restart?

**Comment by andrey18106** [comment]
@ykutovoy That's because of database structure. It's a unique id that auto increments every time.

**Comment by ykutovoy** [comment]
Ok thank You for explanation.
I understand that it lead to much work for You, but may be it is possible convert that unique numbers to correct group numbers in particular task?
something like...
#1548 -> #1
#1549 -> #2
and so on according to actual number of groups

It would be a bit user-friendly :)

**Comment by andrey18106** [comment]
Yea, ok, I'll think about it) Good suggestion.
