### ISSUE TITLE
Auto open next group not working in Firefox 95.0.2 (64-bit)

### ISSUE THREAD

**Issue by RedSackles** [andrey18106/mediadc#39]
First of, great that you implemented this so fast. It will save me so many clicks, thank you.

Auto open next group not working in Firefox 95.0.2 (64-bit)
When using MediaDC in Firefox 95.0.2 (64-bit) the resolved duplicate group is closed but the next one is not opened automatically despite it being set in the settings. In Chrome this functionality works just fine.
I noticed this on my win10 PC 

**To Reproduce**
1. have a duplicate job run resulting in duplicates
2. open the job page using Firefox 95.0.2 (64-bit)
3. make sure "auto open next group" option is enabled
4. ether delete or remove files to resolve the duplicate group

**Expected behavior**
I expect the duplicate group to be closed and the next duplicate group in line to be opened.

Once more in Chrome this works just fine and this is a great feature.

**Comment by andrey18106** [comment]
@RedSackles I have tested it on Firefox 95.0.2 (64-bit, Windows 11) - works fine. Try to clean cache on Firefox browser.

**Comment by RedSackles** [comment]
Oh that is embarrassing.
Yes that resolved the problem in firefox.
