### ISSUE TITLE
Task errors

### ISSUE THREAD

**Issue by cyb31** [andrey18106/mediadc#41]
there is a task error when I run task for vidéos

![Capture d’écran 2021-12-29 164430](https://user-images.githubusercontent.com/45168044/147679345-4e2f9a39-0b98-4895-ad46-5adb55ceede4.png)

I just choose a folder with default setting and video type. For photos, there is no problem, that's works fine.
Do you know what is the bug?

Thanks ;-)

**Comment by andrey18106** [comment]
@cyb31 Video processing requires `ffmpeg` package, that can't be installed automatically (in this case appropriate message displayed on Configuration page). Administrator should install it manually on server.

**Comment by cyb31** [comment]
Hello,
`ffmpeg` package installed and that works fine, thank you!

**Comment by sergeng** [comment]
FFMPEG built from source
ubuntu$ whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg /usr/local/bin/ffmpeg /home/ubuntu/bin/ffmpeg /usr/src/ffmpeginstaller.9.1/ffmpeg.sh

Still complaining
Video processing won't work, video_required packages not installed.
Not installed video_required packages: [ "ffmpeg", "ffprobe" ]
video_required packages can't be installed automatically, this should be done by administrator manually and then recheck installation on this page.

**Comment by bigcat88** [comment]
@sergeng execute `sudo -u www-data ffmpeg` to see if user www-data can see it.

**Comment by sergeng** [comment]
my nginx server username is nginx so
ubuntu$ sudo -u nginx ffmpeg
ffmpeg version N-103105-gb9176dbfb7 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --prefix=/home/ubuntu/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/ubuntu/ffmpeg_build/include --extra-ldflags=-L/home/ubuntu/ffmpeg_build/lib --extra-libs='-lpthread -lm' --ld=g++ --bindir=/home/ubuntu/bin --enable-gpl --enable-gnutls --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libsvtav1 --enable-libdav1d --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      57.  3.100 / 57.  3.100
  libavcodec     59.  3.102 / 59.  3.102
  libavformat    59.  4.101 / 59.  4.101
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  1.103 /  8.  1.103
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
