### ISSUE TITLE
Error: Out of range value for column duration

### ISSUE THREAD

**Issue by kotjarka** [andrey18106/mediadc#47]
After running some bigger task MediaDC returned error:

Task errors
Exception(DataError): `(1264, "Out of range value for column 'duration' at row 1")` 

Task info:
Photos&Videos 59318/60177 files (229.14 GB) (precision: 90%)

**Comment by bigcat88** [comment]
@kotjarka can you add 2 lines of code like in commit  and says if the error is gone?

**Comment by kotjarka** [comment]
@bigcat88 added 5 lines and i can confirm that bug seems to be solved.
Task finished with success, but i should mention that i only re-runed task, not deleted it and started again. 
If i should delete it prior and start from scratch for proper testing please tell me, for my low-power srv it will take some time.
Big thanks for your job.

**Comment by bigcat88** [comment]
@kotjarka no, if it was finished I thinks it is ok. You are free to open new issue if any other problems will occur.
Note: second time it will run much faster till you not change hash algo or hash sizes.
