### ISSUE TITLE
ffmpeg ffprobe built from source not found

### ISSUE THREAD

**Issue by sergeng** [andrey18106/mediadc#48]
FFMPEG built from source
ubuntu$ whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg /usr/local/bin/ffmpeg /home/ubuntu/bin/ffmpeg /usr/src/ffmpeginstaller.9.1/ffmpeg.sh

Still complaining
Video processing won't work, video_required packages not installed.
Not installed video_required packages: [ "ffmpeg", "ffprobe" ]
video_required packages can't be installed automatically, this should be done by administrator manually and then recheck installation on this page.

**Comment by bigcat88** [comment]
@sergeng
wow amazing output, is it it's version? --> `N-103105-gb9176dbfb7`

can you please run `sudo -u nginx ffprobe -version`

**Comment by bigcat88** [comment]
@sergeng you can make changes like in commit(with hands or just replace them from dev branch entirely) and say if it helps.

**Comment by sergeng** [comment]
@bigcat88 working flawlessly after your commit!
Best support ever 🥇 

No Error message on configuration page, see:
<img width="681" alt="2022-02-01_22-06-39" src="https://user-images.githubusercontent.com/8804826/151974495-9b1b69d7-cbe0-40ae-b76a-27d0727070a4.png">

Video job running smoothly, see:
<img width="702" alt="2022-02-01_22-07-07" src="https://user-images.githubusercontent.com/8804826/151974386-e6b51af5-c262-4aae-8155-f22569e8924f.png">
