### ISSUE TITLE
Installation not possible - requirements mismatch

### ISSUE THREAD

**Issue by bcutter** [andrey18106/mediadc#49]
**Describe the bug**
Installing the app using NC App Store is not possible: „…because the following requirements are not met: 64 bit or higher php required.“ But all requirements stated on https://github.com/andrey18106/mediadc/wiki/Installation#requirements are met. Does this app require 64 bit OS?

System:
- PHP 8.0
- Python 3.7.3
- Nextcloud 22
- MariaDB
- 32 bit OS

**Comment by andrey18106** [comment]
@bcutter Yes, this app require 64bit (not all required binaries available for 32bit). Didn't updated that in docs.

**Comment by bcutter** [comment]
Okay thank you for clarifying and updating the requirements section.
