### ISSUE TITLE
Error installing Python packages

### ISSUE THREAD

**Issue by HammyHavoc** [andrey18106/mediadc#51]
**Describe the bug**

**To Reproduce**
1. Click `Install` on the `/apps/mediadc/configuration` after enabling

**Expected behavior**
To install the packages.

**Desktop (please complete the following information):**
 - OS [e.g. iOS] - Windows
 - CPU (architecture) - N/A
 - Browser [e.g. chrome, safari] - Firefox
 - Nextcloud version [e.g. 22] - 22.2.3 in a Docker on Linux 5.10.28-Unraid x86_64
 - Database configuration (without sensitive information) - MariaDB Docker
 - Python version [e.g. 3.9.1] - Not sure
 - MediaDC version [e.g. 0.1.0] - 0.1.8

**Additional context**

Logging:

> [mediadc] Error: [OCA\MediaDC\Service\PythonService] Command executed with error result_code: 127
> 
> GET /apps/mediadc/api/v1/python/check
> from 192.168.1.1 by hammyhavoc at 2022-02-13T04:52:53+00:00
> 
> [mediadc] Error: [OCA\MediaDC\Service\PythonService] Command executed with error result_code: 127
> 
> GET /apps/mediadc/api/v1/python/install
> from 192.168.1.1 by hammyhavoc at 2022-02-13T04:52:56+00:00
> 
> [mediadc] Error: [OCA\MediaDC\Service\PythonService] Command executed with error result_code: 127
> 
> GET /apps/mediadc/api/v1/python/check
> from 192.168.1.1 by hammyhavoc at 2022-02-13T04:53:02+00:00

**Comment by bigcat88** [comment]
@HammyHavoc result_code: 127 == Python not found.
Python must be installed in Docker image(until we release 0.2.0 or 0.2.1 version, that will eliminate that requirement)
If you give more info what docker image you use we can say you with which commands you can install python.

**Comment by Cerial1** [comment]
Hey, im using nextcloud:latest Docker image with Docker 20.10.12 on linux, amd64. Wich command should i run to install phyton?

**Comment by bigcat88** [comment]
#91
