### ISSUE TITLE
How to install the required dependencies and algorithms on a NextCloud Snap ?

### ISSUE THREAD

**Issue by moutasem1989** [andrey18106/mediadc#54]
**Describe the bug**
First install of the MediaDC requires Python dependecies that are not installed:
I am running on a Snap version of NextCloud. When I run MediaDC it premotes me to Configure application dependencies on Configuration page. however, on the Configuration page, MediaDC is inable of installing the required dependencies.
 Nextcloud Log:
`Error | mediadc | [AppUpdateStep] Python dependencies updating error: {"success":false,"installed":false,"required":null,"video_required":null,"optional":null,"boost":null,"available_algorithms":null,"installed_list":null,"errors":["Cant run pip after local install."],"warnings":null}`

**To Reproduce**
1. get and run NextCloud from Snap
2. install and run MediaDC
3. try to add the required dependencies.

**Expected behavior**
dependencies are installed when clicking Install.

**Screenshots**
https://imgur.com/a/oVLVb8K
https://imgur.com/a/HwcIJ2L
https://imgur.com/a/WkLEVSE

**Desktop (please complete the following information):**

```
System info
{
  "nextcloud-version": "22.2.3.0",
  "webserver": "Apache",
  "database": {
    "type": "mysql",
    "version": "8.0.28",
    "size": "63447040"
  },
  "php-version": "8.0.15",
  "php-interpreter": "php",
  "python-version": "3.6.9",
  "python-interpretter-setting": "/usr/bin/python3",
  "os": "Linux",
  "os-release": "5.13.0-28-generic",
  "machine-type": "x86_64",
  "mediadc-version": "0.1.9",
  "mediadc-settings": {
    "remote_filesize_limit": "536870912",
    "installed": {
      "status": false,
      "installed_list": {
        "boost": {
          "hexhamming": {
            "package": "hexhamming",
            "version": "none",
            "location": "none"
          }
        },
        "optional": {
          "pywt": {
            "package": "pywavelets",
            "version": "none",
            "location": "none"
          },
          "scipy": {
            "package": "scipy",
            "version": "none",
            "location": "none"
          },
          "pillow_heif": {
            "package": "pillow_heif",
            "version": "none",
            "location": "none"
          }
        },
        "required": {
          "PIL": {
            "package": "pillow",
            "version": "none",
            "location": "none"
          },
          "numpy": {
            "package": "numpy",
            "version": "none",
            "location": "none"
          }
        }
      },
      "video_required": [
        "ffmpeg",
        "ffprobe"
      ],
      "not_installed_list": {
        "boost": {
          "hexhamming": "hexhamming"
        },
        "optional": {
          "pywt": "pywavelets",
          "scipy": "scipy",
          "pillow_heif": "pillow_heif"
        },
        "required": {
          "PIL": "pillow",
          "numpy": "numpy"
        }
      },
      "available_algorithms": []
    }
  }
}
```

**Comment by andrey18106** [comment]
@moutasem1989 Hi, we don't support snap, until the cloud_py_api framework is released and MediaDC migrated to use it.

**Comment by moutasem1989** [comment]
@andrey18106 is there a timeframe for that?
Thank you again for the great job !

**Comment by andrey18106** [comment]
@moutasem1989 There is no timeframe, as soon as it's ready) We're working on it, but generally planning migration to using of framework for MediaDC 0.2.0-0.2.1 release.

**Comment by bigcat88** [comment]
#91
