### ISSUE TITLE
Cant run pip after local install.

### ISSUE THREAD

**Issue by fromage9747** [andrey18106/mediadc#58]
**Describe the bug**
Cant run pip after local install.

**To Reproduce**
1. Install App through Nextcloud
2. Navigate to app
3. Click on install for the configuration 

**Expected behavior**
Install pillow and numpy successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/23147783/166202104-ef8cefc3-dc10-4334-b901-656fb22fa0c9.png)

**Desktop (please complete the following information):**
 - OS Ubuntu
 - CPU x86
 - Browser Chrome
 - Nextcloud version 23
 - Database configuration mariadb
 - Python version 3.6
 - MediaDC version latest

**Additional context**
I have manually installed pillow and numpy but it has not changed the result:

![image](https://user-images.githubusercontent.com/23147783/166202356-dcb38fe2-026c-4c26-864c-a0882a963de7.png)

**Comment by bigcat88** [comment]
Do you use snap?

**Comment by fromage9747** [comment]
@bigcat88 I do not use snap on my NextCloud instance.  It is not installed.

**Comment by bigcat88** [comment]
@fromage9747 `python3 -m pip -V`  post output of this, so we can check it, maybe some bug in version parsing...

**Comment by fromage9747** [comment]
@bigcat88 

Below is the output:

```
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

![image](https://user-images.githubusercontent.com/23147783/166212786-f0af8db1-b33a-4a2d-9c71-d7781ed8cdbc.png)

**Comment by bigcat88** [comment]
Looks like you have multiply pythons...
You need to provide path to python3.9 in config of MediaDC.

in MediaDC admin settings configure python_command with full proper path to python 3.9
you can search for python probably with `where python3` command in Linux.

P.S.: we will check with python 3.6 for that strange behaviour...

**Comment by fromage9747** [comment]
@bigcat88 Thank you for the feedback.  I will make the changes and get back to you if there are any issues.

**Comment by fromage9747** [comment]
@bigcat88 I have made the required changes and it is working as expected under python3.9.  Thank you for your speedy response and assistance.

**Comment by Airell** [comment]
I'm having the same issue, however, I'm using snap (as asked per 2 May).
Installing with `/usr/bin/python3` results in `Cant run pip after local install.` / `Installation failed. Some server error occured`.
Installing and Checking with `/usr/bin/python3.8` results in `Python version is lower then 3.6.8 or not available (result_code:127)`

```
required    numpy, pillow
optional    scipy, pywavelets, pillow_heif
boost       hexhamming
```
Manual install via pip does not clear the errors.

Ubuntu 20.04.4 LTS
Snap 2.56.2
NC 24.0.3 (24.0.3snap1)
Python 3.8
PIP 22.2.2
MediaDC 1.9

```
~/snap# which python3
/usr/bin/python3
~/snap# ls -la /usr/bin/python3
lrwxrwxrwx 1 root root 9 Mar 13  2020 /usr/bin/python3 -> python3.8
```

**Comment by LucasEngel2** [comment]
I'm having the exact same problems as @Airell.

**Comment by bigcat88** [comment]
@Airell  #91
