### ISSUE TITLE
Jump to page

### ISSUE THREAD

**Issue by kotjarka** [andrey18106/mediadc#63]
**Description**
When working with big number of duplicate groups it will be useful to jump to specified page.

**Example**
![Screenshot_20220604_120224](https://user-images.githubusercontent.com/28064012/171994607-ec4c65dd-4b72-4bb1-aa0e-4ee70f1e49dc.png)
In this case, when want to start from page 423, must first click 422 times next '>' button

**Comment by andrey18106** [comment]
Added "go to page" pagination option in [MediaDC 0.1.10](https://github.com/andrey18106/mediadc/releases/tag/v0.1.10). Closing.
