### ISSUE TITLE
Option to set PHP path to avoid open_basedir errors

### ISSUE THREAD

**Issue by corsch** [andrey18106/mediadc#64]
**Description**
If PHP is hardened by open_basedir you get a lot of "open_basedir restriction in effect." errors in the nextcloud.log

It looks like the MediaDC App is searching for the follolowing forbidden paths for php:
/usr/local/sbin/php7.4.30
/usr/local/bin/php7.4.30
/usr/sbin/php7.4.30
/usr/bin/php7.4.30
/sbin/php7.4.30
/bin/php7.4.30
/usr/local/sbin/php7.4
/usr/local/bin/php7.4
/usr/sbin/php7.4
/usr/bin/php7.4
/sbin/php7.4
/bin/php7.4
/usr/local/sbin/php7
/usr/local/bin/php7
/usr/sbin/php7
/usr/bin/php7
/sbin/php7
/bin/php7

In my case the correct PHP binary would be in /usr/bin/php

This could be fixed by an configuration option to set the correct PHP binary.

**Comment by andrey18106** [comment]
Added PHP path option in [MediaDC 0.1.10](https://github.com/andrey18106/mediadc/releases/tag/v0.1.10). Closing.
