### ISSUE TITLE
Could not resolve ...

### ISSUE THREAD

**Issue by mderasse** [andrey18106/mediadc#67]
Hello,

**Describe the bug**
Following the installation of the app (manually or through the nextcloud apps) i'm not able to configure / use the application.
MediaDC settings are not showing up and call to apps/mediadc/api/v1/settings return 500

**To Reproduce**
1. Install the apps
2. Go to Media DC settings

**Environment:**
 - OS: Docker (nextcloud:apache + needed package)
 - CPU: x86
 - Nextcloud version: 24.0.3
 - Database configuration: Postgres / Mysql (tried both)
 - Python version: 3.9.2
 - MediaDC version [0.1.9

**Additional context**
**Logs:** 
```
Error: Exception: Repair step 'OCA\MediaDC\Migration\AppUpdateStep' can't be instantiated: Could not resolve pythonService! Class "pythonService" does not exist at <<closure>>

0. /var/www/html/lib/private/legacy/OC_App.php line 1075
   OC\Repair->addStep("OCA\\MediaDC\\Migration\\AppUpdateStep")
1. /var/www/html/lib/private/Installer.php line 149
   OC_App::executeRepairSteps("mediadc", ["OCA\\MediaDC\\ ... "])
2. /var/www/html/apps/settings/lib/Controller/AppSettingsController.php line 451
   OC\Installer->installApp("mediadc")
3. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 225
   OCA\Settings\Controller\AppSettingsController->enableApps(["mediadc"], [])
4. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 133
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
5. /var/www/html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
6. /var/www/html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, ["settings.AppSettings.enableApps"])
7. /var/www/html/lib/base.php line 1023
   OC\Route\Router->match("/settings/apps/enable")
8. /var/www/html/index.php line 36
   OC::handleRequest()

POST /settings/apps/enable
```

I'm also having the "Could not resolve" issue for:
- OCA\ServerInfo\DatabaseStatistics
- databaseStatistics
- utils

Any idea how to resolve that ?

Thank you !

**Comment by andrey18106** [comment]
A [serverinfo](https://github.com/nextcloud/serverinfo) app is required for MediaDC settings (for the bug report section).

You can manually install it:

`git clone https://github.com/nextcloud/serverinfo.git --depth 1 -b $NEXTCLOUD_VERSION nextcloud/apps/serverinfo`
`php -f nextcloud/occ app:enable serverinfo`

where `$NEXTCLOUD_VERSION` - your Nextcloud server version tag `v24.0.3`

After that, you need to reinstall MediaDC (as the database could possibly not be initialized because of this bug).

**Comment by mderasse** [comment]
Thanks for the quick reply.

I actually already had serverinfo but it wasn't enabled ...
Enabling it and reinstalling MediaDC did fix the issue.

Thank you for your amazing work and your help !

Have a nice day!

**Comment by tbarbette** [comment]
I ran into this too. If we're not alone, maybe the error could be caught?
