### ISSUE TITLE
Use Transifex for continuous translation please

### ISSUE THREAD

**Issue by p-bo** [andrey18106/mediadc#71]
Hello,
would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
...and gain benefits from work of whole Nextcloud translators community for users of your app please?

For instance:

- much more translators will get involved, because without it, they will newer even know about possibility to translate this app - example of benefits for project known in this manner for community of Nextcloud translators (app with recently added to this workflow, based on same request as this one): https://github.com/H2CK/oidc/commit/937fc37d7797fecc9f4f49e12a154cd8987cf99c (se this and ongoing Nextcloud bot commits - translation of app is getting completed/improved in no time)
- also, as app is evolving, when some string(s) in app is/are changed/added, in case of continuous translation workflow translators are noticed intermediately and strings are translated before new version is released. In contrast with situation, that this change (in source strings) is only silently published in git repo and no one will (get) notice(d) till never version with untranslated strings get released (proactive vs retroactive).
- when one (of translators) will during using this app notice possibility to translate something in better manner, it is much efficient (especially for minor changes) to do this in translation tool than edit file directly in git. For example in case of one letter changes (misspelled words, etc.) has change directly in git such overhead (many steps to change just one letter), that these type of tweaks are rare due this (loss of quality for users)

To conclude: with continuous translation workflow, result is, that users of your app are getting more complete and more polished localization, so their user experience is much more pleasant.

Thanks :-)

**Comment by andrey18106** [comment]
@p-bo Added continuous translation, now it's available on [Nextcloud Transifex Project](https://www.transifex.com/nextcloud/nextcloud/mediadc/).

**Comment by p-bo** [comment]
Many thanks @andrey18106 and @nickvergessen - appreciated! :-)

**Comment by roliverio** [comment]
Hi, would like to know if the string mappings currently under l10n/*.js should be expanded to effectively use the rest of strings that belong to the app (currently 224). Thanks.

**Comment by nickvergessen** [comment]
No, l10n/ is overwritten every night by the sync bot. If something is missing in the app the source code needs to be modified so that our translation tool can correctly extract it into the files that are then synced and turned into the l10n files afterwards

**Comment by roliverio** [comment]
Sorry, maybe my comment was not clear enough, i do know that the bot updates translations automatically, but my question was more geared towards knowing exactly what you're now saying, you'll need to modify the code to include the rest of the strings that are missing even if they're already on Transifex. Thanks! (working on them as we speak)

**Comment by p-bo** [comment]
@roliverio On Transifex are strings from newest revision of source code, whereas you are using latest released version. Thus it should be, that strings, that were translated after release was done, are translated on Transifex, but not in current release (which is thus behind). Don't worry, just wait for newer release, which will have newest translations merged. If you want to test how strings fits, you can try night builds.

**Comment by p-bo** [comment]
@roliverio maybe understand now:
![obrazek](https://user-images.githubusercontent.com/12208593/198879135-6bb0d4b9-fd8b-4d1f-8089-01f78296b7f2.png)
It seems, that especially for admin settings, source strings are not extracted from source code by bot to Transifex at all (these strings are not present on Transifex, thus not in .js and .json files). Example of such strings:
https://github.com/andrey18106/mediadc/search?q=Full+path+to+python+interpreter
Probably is needed to add t('myapp', (into javascript code and analogically into php one) as stated in:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#javascript
