### ISSUE TITLE
Make app compatible with NC v25

### ISSUE THREAD

**Issue by rakekniven** [andrey18106/mediadc#73]
Today NC25 is out and this app needs some love ❤️ .

**Comment by phil-lipp** [comment]
It's working quite fine for me, or at least it appears so. I can set up scans and they finish. But deleting them is tedious, because I can't scroll downwards in the /apps/mediadc/tasks window

**Comment by andrey18106** [comment]
@phil-lipp Yes, it'll work, but Frontend part have breaking changes in NC25 (scroll won't work) and MediaDC for now is not supported officially with Nextcloud 25 version. Update for that is in development. Stay tuned.

**Comment by datenleck** [comment]
I can't wait! I'm already biting my fingernails... ;-)
Is there a quick fix to solve the scrolling problem?
Thanks!

**Comment by andrey18106** [comment]
[MediaDC 0.2.0](https://github.com/andrey18106/mediadc/releases/tag/v0.2.0) for Nextcloud 25 now available.
