### ISSUE TITLE
Typo fix for string

### ISSUE THREAD

**Issue by roliverio** [andrey18106/mediadc#80]
Hi!

Please fix the "updateing" string on:

https://github.com/andrey18106/mediadc/blob/main/js/mediadc-settings.js
https://github.com/andrey18106/mediadc/blob/main/js/mediadc-settings.js.map
https://github.com/andrey18106/mediadc/blob/main/src/components/settings/AdminSettings.vue

To "updating"

Proper change to the l10n mappings is also required.

Thanks!

**Comment by andrey18106** [comment]
@roliverio Hi! Nice catch, thanks!
