### ISSUE TITLE
Typos fix for appropiate translation.

### ISSUE THREAD

**Issue by roliverio** [andrey18106/mediadc#82]
Typo fix:  

**dependecies** -> _dependencies_

On:

js/mediadc-src_views_Configuration_vue.js.map
js/mediadc-src_views_Configuration_vue.js
lib/Controller/PythonController.php

**occured** --> _occurred_

On:

js/mediadc-settings.js
js/mediadc-main.js.map
js/mediadc-src_views_CollectorDetails_vue.js
js/mediadc-settings.js.map
js/mediadc-src_views_Collector_vue.js
js/mediadc-src_views_Collector_vue.js.map
js/mediadc-src_views_CollectorDetails_vue.js.map
js/mediadc-main.js

**Package list deleting failed. Some server error occured** -> _Package list deletion failed. Some server error occurred_

On:

js/mediadc-main.js.map
js/mediadc-main.js

**Comment by andrey18106** [comment]
@roliverio `js` folder - is for js binaries builded from `src`. So, it's enough to change typos in `src` - with app release and while in developing these js-binaries updated regulary.
