### ISSUE TITLE
`dhash` is not available.

### ISSUE THREAD

**Issue by datenleck** [andrey18106/mediadc#85]
Hi,

I installed the App on my NC 25.0.1, 
Linux Debian 11, PHP-FPM 8.0.25, Python 3.9

I removed any python 2 software, but the error appears after a few seconds.

The error message "`dhash` is not available." appears in the MediaDC error.
![grafik](https://user-images.githubusercontent.com/47418901/201621703-db8fbef1-0db1-41b5-bc76-e973796a2847.png)

**Comment by bigcat88** [comment]
do you have installed numpy and pillow packages?

**Comment by datenleck** [comment]
Thank you!
apt install python3-numpy/stable
apt install python3-willow/stable
This did the trick obviously!

**Comment by bigcat88** [comment]
> apt install python3-willow/stable

Just a note: this project use **Pillow**, not a **Willow**

**Comment by datenleck** [comment]
Yes, but I didn't find Pillow... and Willow seems to include Pillow

# pip3 search pillow
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.

# apt search python | grep -i Pillow
python3-pypillowfight/stable 0.3.0-4+b2 amd64
  Python 3 bindings for libpillowfight
  Python image library combining Pillow, Wand and OpenCV (Python 3)
