### ISSUE TITLE
Need testers for Beta-0.3.0

### ISSUE THREAD

**Issue by bigcat88** [andrey18106/mediadc#91]
We've released an alpha-beta version, but we're looking for users who can test a version that doesn't require Python installation or dependencies.

Write here your:
1. OS
2. CPU type(x86_64, arm8, arm7)
3. Type of Nextcloud installation (docker, snap, etc.)
4. Logs with errors(if any)

Note:
**FreeBSD is not currently supported.** (in future with such type we can add support but need an access to system with FreeBSD to build binaries or $ to rent some VPS)

**Comment by 2br-2b** [comment]
I'm up for testing this. How do I access your program's beta?

- Ubuntu
- x86_64
- Snap
- Haven't installed beta yet

**Comment by 2br-2b** [comment]
I can confirm, however, that I am running MediaDC v0.1.10

**Comment by andrey18106** [comment]
@2br-2b MediaDC starting from 0.2.0 version requires Nextcloud 25+.

Nextcloud snap is still on NC24 because of some bugs in NC25, they are waiting next NC25 updates to upgrade snap.
