### ISSUE TITLE
Cannot use OCC if I enable MediaDC in NC 25

### ISSUE THREAD

**Issue by TtuxX** [andrey18106/mediadc#93]
**Describe the bug**
First, thank you very much for your great app and great idea :)
My issue is that I cannot ose OCC on Nextcloud 25.0.2 when I enable MediaDC.

I get exactly this error: https://github.com/nextcloud/server/issues/31330

**To Reproduce**
1. Have NC 25.0.2
2. Enable MediaDC
3. See that OCC does not work anymore, with errors like: https://github.com/nextcloud/server/issues/31330
4. Need to disable MediaDC to have a working OCC instance

**Expected behavior**
MediaDC should not conflict wit NC 25.0.2 nor OCC

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: TrueNAS Core
 - CPU: x64
 - Nextcloud version: 25.0.2
 - Database configuration: mysql  Ver 8.0.31 for FreeBSD12.3 on amd64 (Source distribution)
 - Python version: Python 3.9.15
 - MediaDC version: 0.2.0

**Additional context**
N/A.

Thank you very much in advance for your kind help!

Best regards

**Comment by bigcat88** [comment]
Unfortunately, we do not currently support FreeBSD.
